default_stages: [ commit, merge-commit, push, prepare-commit-msg, commit-msg,
                  post-checkout, post-commit, post-merge, post-rewrite ]
exclude: |
  (?x)(LICENSE|
  \.(html|csv|svg)$)
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black-jupyter
        fail_fast: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed.
      - id: check-case-conflict      # Check for files with names that would conflict on a
                                     # case-insensitive filesystem like macOS HFS+ or Windows
                                     # FAT.
      - id: check-merge-conflict     # Check for files that contain merge conflict strings.
      - id: check-symlinks           # checks for symlinks which do not point to anything.
      - id: check-yaml               # checks yaml files for parseable syntax.
      - id: destroyed-symlinks       # Detects symlinks which are changed to regular
                                     # files with a content of a path which that symlink was pointing to.
      - id: detect-private-key       # Checks for the existence of private keys.
      - id: end-of-file-fixer        # Makes sure files end in a newline and only a newline.
      - id: mixed-line-ending        # Replaces or checks mixed line ending.
      - id: trailing-whitespace      # Trims trailing whitespace.
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        types: [rust]
        language: system
